services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hasher-website
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      # Token autoryzacyjny wygenerowany w panelu Cloudflare
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - web-app